### ISSUE TITLE
Error using with Redis

### ISSUE THREAD

**Issue by jasuten** [integer-net/magento2-session-unblocker#12]
When I first installed it I had the following error report:
Warning: ini_set(): Cannot find save handler 'redis' in /app\/code\/Scandiweb\/SessionFix\/Plugin\/SessionStartPlugin.php on line 270...

The fix was just needing the PHP extension (phpredis) installed, but it may be a good idea to put a note in the readme that it is a requirement if you are using redis for sessions.

**Comment by wigman** [comment]
I am a little bit confused.
- the offending file is not in our module
- how does our module add a dependency to `phpredis`, isn't that just a requirement for Redis to work with Magento, by default? Our module should in theory also work with other session types then Redis...
